### PR TITLE
Use NVM NodeJS aliases for NodeJS 4.x.x and 5.x.x branches

### PR DESCRIPTION
**Pull request by ntwb**
See https://github.com/gruntjs/grunt-legacy-util/pull/9#issuecomment-173440880

### CODE REVIEW

**Comment by shama** [comment]
Would you mind updating to keep the specific versions of `4.x` and keep the tagged `5`?

**Comment by ntwb** [comment]
Done :+1:

**Comment by shama** [comment]
Thanks!

**Comment by ntwb** [comment]
:+1:

**Pull request merged**
